### ISSUE TITLE
[feature needed]catch the hover target when dragging

### ISSUE THREAD

**Issue by Jinjiang** [googlearchive/core-drag-drop#8]
As the title described. the `this.dragInfo`:

```
listen('trackstart', 'trackStart');
listen('track', 'track');
listen('trackend', 'trackEnd');
```

has no hover target. So there's no way to make sure the element I will drop if I release my mouse here.

I found that global `addEventListener('mousemove', ...)` can do this and send a pull request. But I've no idea about the perfect way.

Thanks.

**Comment by saurshaz** [comment]
+1

**Comment by untouchable** [comment]
+1
